name: donghuahub_app 
description: App para visualizar animes do DonghuaHub

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  lottie: ^3.1.2
  cached_network_image: ^3.3.1
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.2
  video_player: ^2.8.6  
  chewie: ^1.8.0      
  carousel_slider:
    git:
      url: https://github.com/serenader2014/flutter_carousel_slider.git
      ref: master
  dio: ^5.4.3+1            
  path_provider: ^2.1.3 
  jwt_decode: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
